# Generated by Django 5.1.2 on 2024-10-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='fecha_publicacion',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='fecha_comentario',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='contenido',
            field=models.TextField(),
        ),
    ]
